[project]
name = "tennis_ml"
version = "0.1.0"
description = "Tiny demo project"
requires-python = ">=3.13"

# Runtime dependencies
dependencies = [
"numpy>=1.26",
"pandas>=2.2",
"matplotlib>=3.9",
"scikit-learn>=1.4",
"xgboost>=1.7",
"fastparquet>=0.8",
"jupyterlab>=4.0",
"pyarrow>=12.0",
]